- name: Install prerequired packages
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true

- name: Copy wsl configuration
  become: true
  shell: curl {{ gists.wslconf }} > /etc/wsl.conf

- name: Remove old docker and its dependencies
  become: true
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Add docker's official GPG (GNU Privacy Guard) key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

- name: Register architecture type
  shell: dpkg --print-architecture
  register: architecture

- name: Add docker apt-package repository
  become: true
  apt_repository:
    repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    update_cache: yes

- name: Install docker and other important packages
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - build-essential
      - python3-pip
    update_cache: true

- name: Install python pexpect
  become: true
  apt:
    name: python3-pexpect
    update_cache: true

- name: Automate docker startup
  script: docker_init.sh {{ gists.docker }}

- name: Edit sudoes for docker service
  script: docker_sudo.sh

- name: Add user to docker group
  become: true
  shell: "usermod -aG docker {{ lookup('env', 'USER') }}"

- name: Delete existing ssh key
  shell: rm ~/.ssh/id_ed25519 ~/.ssh/id_ed25519.pub
  ignore_errors: true

- name: Generate new ssh key
  expect:
    command: ssh-keygen -t ed25519 -C "{{ mail }}"
    responses:
      ".*Enter file in which to save the key": "\n"
      "Enter passphrase": "{{ passphrase }}"
      "Enter same passphrase": "{{ passphrase }}"
    echo: true

- name: Create github sub directory in ~/.ssh
  file:
    path: ~/.ssh/github
    state: directory
    mode: '0700'

- name: Move ssh key files
  shell: mv ~/.ssh/id_ed25519* ~/.ssh/github

- name: Install keychain
  become: true
  apt:
    name: keychain
    state: present

- name: Initialize ssh agent when wsl starts
  script: sshagent_init.sh {{ gists.sshagent }}

- name: Add ssh config to read github sub directory
  shell: curl {{ gists.sshconf }} > ~/.ssh/config

- name: Add git config for ssh connection
  shell: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

- name: All process completed
  debug:
    msg: All installation done. Please don't forget to add your public key in github setting.